# Generated by Django 5.2.8 on 2026-02-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_review_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
